apiVersion: v1
kind: Secret
metadata:
  name: dbsecret
type: Opaque
data:
  username: YWRtaW4K
  password: cGE4NzQzMXdvcmQK
---
apiVersion: v1
kind: Pod
metadata:
  name: myservice
spec:
  containers:
  - name: service1
    image: service1:latest
    imagePullPolicy: IfNotPresent
    ports:
      - containerPort: 3000
    env:
      - name: DB_USER
        valueFrom:
          secretKeyRef:
            name: dbsecret
            key: username
      - name: DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: dbsecret
            key: password